Fixing database connection using postgres user...
Database already exists
NOTICE:  relation "users" already exists, skipping
CREATE TABLE
NOTICE:  relation "products" already exists, skipping
CREATE TABLE
NOTICE:  relation "tickets" already exists, skipping
CREATE TABLE
NOTICE:  relation "changes" already exists, skipping
CREATE TABLE
CREATE TABLE
CREATE INDEX
ERROR:  update or delete on table "users" violates foreign key constraint "approval_routing_approver_id_fkey" on table "approval_routing"
DETAIL:  Key (id)=(3) is still referenced from table "approval_routing".
ERROR:  column "department" of relation "users" does not exist
LINE 1: ...NTO users (username, email, name, password, role, department...
                                                             ^
ERROR:  column "owner" of relation "products" does not exist
LINE 1: ...NSERT INTO products (name, description, category, owner, act...
                                                             ^
ERROR:  column "product_id" of relation "tickets" does not exist
LINE 1: ...TO tickets (title, description, status, priority, product_id...
                                                             ^
     ?column?
------------------
 Users created: 4
(1 row)

 username |    role
----------+------------
 admin    | admin
 support  | technician
 manager  | manager
 user     | user
(4 rows)

[PM2] Applying action deleteProcessId on app [itservicedesk](ids: [ 0 ])
[PM2] [itservicedesk](0) ✓
┌────┬───────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name      │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
└────┴───────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
[PM2][WARN] Applications itservicedesk not running, starting...
[PM2] App [itservicedesk] launched (1 instances)
┌────┬──────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name             │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼──────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0  │ itservicedesk    │ default     │ 1.0.0   │ fork    │ 175277   │ 0s     │ 0    │ online    │ 0%       │ 19.1mb   │ ubuntu   │ disabled │
└────┴──────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
Testing application...
Application running
Auth failed: {"message":"Internal server error"}
